#!/usr/bin/php
<?php

require_once dirname(__FILE__) . '/lib/finder.php';
require_once dirname(__FILE__) . '/lib/parser.php';
require_once dirname(__FILE__) . '/lib/stream.php';

$output_file = 'docs.html';
if ( !empty($argv[2]) ) {
	$output_file = $argv[2];
}

$stream = new HTMLStream($output_file);

if ( is_dir($argv[1]) ) {
	$finder = new TomDocFinder($argv[1]);
	$files = $finder->find('*.php');

	foreach ( (array) $files as $file ) {
		$parser = new TomDocParser($file);

		$parser->parse();

		$parser->output(&$stream);
	}
}

if ( is_file($argv[1]) ) {
	$parser = new TomDocParser($argv[1]);

	$parser->parse();

	$parser->output(&$stream);
}